project:
  type: book

book:
  title: "DS_6021_Predictive_Modeling_Maxwell_Braseth_First_Quarto_Project"
  author: "Maxwell Braseth"
  date: "5/26/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - HW1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



